
title: Kedy's Page
theme: jekyll-theme-slate
logo: me.jpg
owner:
  name: Kedy Edme
  avatar: me.jpg
  bio: My personal website where I will share science related projects
  twitter: www.twitter.com/kekeedme
