
title: Kedy's Page
theme: jekyll-theme-slate
owner: 
  name: Kedy Edme
  avatar: #will be a picture of myself
  bio: My personal website where I will share science related projects
  twitter: www.twitter.com/kekeedme
