layout: default
title: Kedy's Page
theme: jekyll-theme-leap-day
avatar: me.jpg
markdown: kramdown 
description: My personal website
owner:
  name: Kedy Edme
  bio: My personal website where I will share science related projects
  twitter: www.twitter.com/kekeedme

kramdown:
  math_engine       : mathjax
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : 1..6
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
